- block:
  - name: Ensure UFW firewall is installed
    apt:
      name:
        - ufw
      state: present

  - name: Allow SSH traffic through firewall
    ufw:
      rule: allow
      name: OpenSSH

  - name: Block all incoming traffic by default
    ufw:
      state: enabled
      direction: incoming
      policy: deny

  - name: Allow all outgoing traffic by default
    ufw:
      state: enabled
      direction: outgoing
      policy: allow

  - name: Allow raphael/Nginx HTTP traffic through the firewall
    ufw:
      rule: allow
      to_port: 80
      proto: tcp
      comment: Judgels Raphael/Nginx HTTP

  - name: Allow raphael/Nginx HTTPS traffic through the firewall
    ufw:
      rule: allow
      to_port: 443
      proto: tcp
      comment: Judgels Raphael/Nginx HTTPS

  - name: Allow phpMyAdmin login traffic through the firewall
    ufw:
      rule: allow
      to_port: 3306
      src: 172.17.0.0/24
      proto: tcp
      comment: phpMyAdmin login

  tags:
    - firewall
