- name: Generate nginx config optimization
  template:
    src: "{{ playbook_dir}}/../conf/nginx.conf.j2"
    dest: /etc/nginx/conf.d/judgels.conf

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
