- block:
    - name: Build jophiel image and push it to DockerHub
      docker_image:
        path: "{{ playbook_dir }}/../../../judgels-backends/jophiel/jophiel-dist"
        name: judgels/jophiel
        force: yes
        push: yes
        buildargs:
          VCS_REF: "{{ lookup('env', 'TRAVIS_COMMIT') }}"
