- block:
    - name: Build judgels server image and push it to GitHub container registry
      docker_image:
        source: build
        force_source: yes
        name: "ghcr.io/ia-toki/judgels/server:osnp-2024"
        push: yes
        build:
          path: "{{ playbook_dir }}/../../../judgels-backends/judgels-server-app"
          args:
            VCS_REF: "{{ lookup('env', 'GITHUB_SHA') }}"
