- hosts: judgels
  gather_facts: false
  tasks:
    - name: Create auth logs directory
      file:
        path: "{{ dump_dir }}/auth/{{ inventory_hostname }}"
        state: directory
      delegate_to: localhost
      connection: local

    - name: Download auth logs
      synchronize:
        mode: pull
        src: /var/log/auth.log
        dest: "{{ dump_dir }}/auth/{{ inventory_hostname }}/"

- hosts: database
  gather_facts: false
  tasks:
    - name: Create MySQL logs directory
      file:
        path: "{{ dump_dir }}/mysql/{{ inventory_hostname }}/logs"
        state: directory
      delegate_to: localhost
      connection: local

    - name: Download MySQL logs
      synchronize:
        mode: pull
        src: /var/log/mysql/
        dest: "{{ dump_dir }}/mysql/{{ inventory_hostname }}/logs"

- hosts: uriel
  gather_facts: false
  tasks:
    - name: Create uriel logs directory
      file:
        path: "{{ dump_dir }}/uriel/{{ inventory_hostname }}/logs"
        state: directory
      delegate_to: localhost
      connection: local

    - name: Download uriel logs
      synchronize:
        mode: pull
        src: /judgels/uriel/var/log/
        dest: "{{ dump_dir }}/uriel/{{ inventory_hostname }}/logs"

- hosts: jophiel
  gather_facts: false
  tasks:
    - name: Create jophiel logs directory
      file:
        path: "{{ dump_dir }}/jophiel/{{ inventory_hostname }}/logs"
        state: directory
      delegate_to: localhost
      connection: local

    - name: Download jophiel logs
      synchronize:
        mode: pull
        src: /judgels/jophiel/var/log/
        dest: "{{ dump_dir }}/jophiel/{{ inventory_hostname }}/logs"

- hosts: sandalphon
  gather_facts: false
  tasks:
    - name: Create sandalphon logs directory
      file:
        path: "{{ dump_dir }}/sandalphon/{{ inventory_hostname }}/logs"
        state: directory
      delegate_to: localhost
      connection: local

    - name: Download sandalphon logs
      synchronize:
        mode: pull
        src: /judgels/sandalphon/var/log/
        dest: "{{ dump_dir }}/sandalphon/{{ inventory_hostname }}/logs"

- hosts: sealtiel
  gather_facts: false
  tasks:
    - name: Create sealtiel logs directory
      file:
        path: "{{ dump_dir }}/sealtiel/{{ inventory_hostname }}/logs"
        state: directory
      delegate_to: localhost
      connection: local

    - name: Download sealtiel logs
      synchronize:
        mode: pull
        src: /judgels/sealtiel/var/log/
        dest: "{{ dump_dir }}/sealtiel/{{ inventory_hostname }}/logs"

- hosts: gabriel
  gather_facts: false
  tasks:
    - name: Create gabriel logs directory
      file:
        path: "{{ dump_dir }}/gabriel/{{ inventory_hostname }}/logs"
        state: directory
      delegate_to: localhost
      connection: local

    - name: Download gabriel logs
      synchronize:
        mode: pull
        src: /judgels/gabriel/var/log/
        dest: "{{ dump_dir }}/gabriel/{{ inventory_hostname }}/logs"

- hosts: jerahmeel
  gather_facts: false
  tasks:
    - name: Create jerahmeel logs directory
      file:
        path: "{{ dump_dir }}/jerahmeel/{{ inventory_hostname }}/logs"
        state: directory
      delegate_to: localhost
      connection: local

    - name: Download jerahmeel logs
      synchronize:
        mode: pull
        src: /judgels/jerahmeel/var/log/
        dest: "{{ dump_dir }}/jerahmeel/{{ inventory_hostname }}/logs"
