- name: Install nginx
  package:
    name: nginx
    state: present
  notify: Restart nginx

- name: Enable nginx to start automatically on boot
  service:
    name: nginx
    enabled: yes

- name: Disable default sites config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Generate judgels nginx config
  template:
    src: "{{ playbook_dir}}/../conf/nginx.conf.j2"
    dest: /etc/nginx/conf.d/judgels.conf
  notify: Restart nginx

- name: Allow nginx HTTP traffic through the firewall
  ufw:
    rule: allow
    to_port: "80"
    proto: tcp
    comment: judgels nginx http

- name: Allow nginx HTTPS traffic through the firewall
  ufw:
    rule: allow
    to_port: "443"
    proto: tcp
    comment: judgels nginx https

- name: Set up certbot
  include_tasks: setup_certbot.yml
  tags: always

- name: Configure domains
  include_tasks: configure_domain.yml
  loop: "{{ domains }}"
  loop_control:
    loop_var: domain
  tags: always
