package judgels.persistence.dao;

import judgels.persistence.model.TrainingProgrammingSubmissionModel;

public interface TrainingProgrammingSubmissionDao extends BaseProgrammingSubmissionDao<TrainingProgrammingSubmissionModel> {}
