import { APP_CONFIG } from '../../../conf';
import { Page } from '../pagination';
import { get } from '../http';
import { Scoreboard } from './scoreboard';

export interface Contest {
  id: number;
  jid: string;
  name: string;
  style: ContestStyle;
}

export enum ContestStyle {
  ICPC = 'ICPC',
  IOI = 'IOI',
}

export interface ContestList extends Page<Contest> {}

export function createContestAPI() {
  const baseURL = `${APP_CONFIG.apiUrls.uriel}/contests`;

  return {
    getContests: (page: number, pageSize: number): Promise<ContestList> => {
      return get(`${baseURL}?page=${page}&pageSize=${pageSize}`);
    },

    getContest: (contestJid: string): Promise<Contest> => {
      return get(`${baseURL}/${contestJid}`);
    },

    getContestScoreboard: (contestJid: string): Promise<Scoreboard> => {
      return Promise.resolve({
        state: {
          problemJids: [
            'JIDPROGECA11y3YOxbBW692uA2g',
            'JIDPROGHvbGs2iiYHdPpoaNkBLC',
            'JIDPROGI21je107wM5DfB6HX3dS',
            'JIDPROGyFLDt0hQ1fHX4pVUsPj2',
          ],
          problemAliases: ['A', 'B', 'C', 'D'],
          contestantJids: [
            'JIDUSERkCDlQedJnAffc8ucgQtC',
            'JIDUSERViHvJNi8EhnNxjUK5ZyC',
            'JIDUSERwePsXnTv0jxTcrrce0Jw',
            'JIDUSERRF9rBojUG04DSot4VGsc',
            'JIDUSER60MK5c4MOMOfkdf53Ic0',
            'JIDUSERtORqD8jwG0VvBtmZN9j3',
            'JIDUSER7iAYDteUK3UwwIL2cczM',
            'JIDUSERxzoyyxjddCEkJbyfiiPq',
            'JIDUSERD7Ngp13Cga22wnUqoRdB',
            'JIDUSERxUqhX6BIfzerWDHWphK4',
            'JIDUSEReHkKO0DV0KgXdtqAkoXd',
            'JIDUSERMZCSsueJmWtM5dQIkSOj',
            'JIDUSERLHBNbjk5qul9Bpo8GmTX',
            'JIDUSER3Jhvm5QLZQ3VcWMkw0vN',
            'JIDUSERGorv5qj5z89TdGKKhtRG',
            'JIDUSERtDpxAAX1zVxlSdN7lCzS',
            'JIDUSERRcheGWFnarBwDfdjYFa7',
            'JIDUSERS411IaQ6lJhDtefKhFUd',
            'JIDUSERpWfBjoZumnBAKLJtS1xF',
            'JIDUSERoKzCRg1P0h1cpcD5s41c',
            'JIDUSER85iNAEW9xc9UGav9szTE',
            'JIDUSERUKGmqNcFIqcSsrne988Y',
            'JIDUSERhyRz01fskYF7Gj2XLnZt',
            'JIDUSER879uH95bu810RPzgLNTb',
            'JIDUSER42qWD0mRHUBoQMKZDpAF',
            'JIDUSERGDm3mCGpS7EbKzTvE9HW',
            'JIDUSERE5wWRfP11XQf6fzExoba',
            'JIDUSERSqxFDHD77z1nlmDW7OxD',
            'JIDUSERXJ1gWHRj4cTPTsUciuRo',
            'JIDUSERs1V040j130IYPEgxwT3j',
            'JIDUSERqRUN48KalIyixTohoIHm',
            'JIDUSERr6x104iovUOK9yMSbGoS',
            'JIDUSEROj48xZk6KsRZy5s0QmfB',
            'JIDUSERienP80NzcpzJRNn18BLY',
            'JIDUSERRhz06Gl6SXmcv6ZUPAyu',
            'JIDUSER1x5wqMWEWEvGnovq7sEi',
            'JIDUSERoAyCGh5EKkmEWGXQKO96',
            'JIDUSERgUoEpjt47hKFz5ij6WNS',
            'JIDUSERpUSFkNO1M2D1sRIN84CQ',
            'JIDUSERGlmCGUBw0xYxzV2u2X6l',
            'JIDUSERh8wo7Brlikbdg9McXQUt',
            'JIDUSERJcxgDZopxunhw90d9iOs',
            'JIDUSERkeeAF95bYeD6u97mAxzg',
            'JIDUSERPxrj0ieeBzpp1flGqdPU',
            'JIDUSERtY060SxILRxz550xcoLo',
            'JIDUSERhFJ5AWTo1ytMJocljeOv',
            'JIDUSERgVH6XjgbXOgSwVBfZ9og',
            'JIDUSER6KyCDKKgKUAw046qhcZG',
            'JIDUSERsPS40FNl2K6RIYKpeXsN',
            'JIDUSER81DZGVqCEad8H4J8rVAQ',
            'JIDUSERYZiw8A3jiXwYOrDrnCy7',
            'JIDUSERn4IxlLzfGuBUpFBy7UyQ',
            'JIDUSERhI2lC8C20KE2RDrR0dGW',
            'JIDUSER33KcvmaGmuetUCBpNX7G',
            'JIDUSERujnnfIDDZitVfyzs6LUg',
            'JIDUSERZv70HP159YTrBfRlzW9p',
            'JIDUSERiH4xoeadIspc3gT7uco4',
            'JIDUSER9oCEQ1fKKtE0JnOZR29K',
            'JIDUSERqwbgjFOfFjhJ0MtKotW2',
            'JIDUSERJdEZFy6xHecsRTPFYk3H',
            'JIDUSER0epnAT3IcXQ1nbYkCfOm',
            'JIDUSERXWcpYoJpRKk6hhbgueoY',
            'JIDUSERlikfw0HNMEGJ5HHd6lGE',
            'JIDUSERXOZYXggJhdm2RGTL2egV',
            'JIDUSERPZWw75l5mNsTVEOejf4n',
            'JIDUSERIzEJ6c4zrIouxqzXlPWg',
            'JIDUSERmwcEsRnPtQyf936SUPw0',
            'JIDUSERc6seSfTUJeSs0Jsi6uYB',
            'JIDUSEROynAxKKoyXlzpLsMWnfd',
            'JIDUSERKiRDEllRg7skebP6UReR',
            'JIDUSER8RTu0pGquVp25C3NTKUy',
            'JIDUSERSkRMybWchRPsvT1VGr9H',
            'JIDUSERhVBTSxwCH2GSyK7I6gv2',
            'JIDUSERFHDMUOtwvOTaNE0GaqFo',
            'JIDUSERtgjLPPOIGjWWdUcCpgwD',
            'JIDUSERJLZZSzn5PY5GzwsThtZu',
            'JIDUSER7zp3Oyzz5AXvvgo3BPL4',
            'JIDUSERwCPFoF0Q95jnl9qEbaMP',
            'JIDUSERVyLJL2DjuA3Ys54yuLV0',
            'JIDUSER0nMdNeSltPiYfrGSE3pZ',
            'JIDUSERTBoPsmm8OZmEr16TbBjY',
            'JIDUSERSStscU2RqwX7DKjjk3dD',
            'JIDUSERqCYx5bNEiqDUZmHh2gwt',
            'JIDUSER4yCUZyjlw2D3fuEzu7zD',
            'JIDUSER1I8LpKYrMiclFRuGTYrS',
            'JIDUSERlmInid8Lmj3Fyv6rdWeq',
            'JIDUSERmzA41uQY72KePflz6eFl',
            'JIDUSERUzkzdjaDAqM596JLhFt9',
            'JIDUSERoWFiYqBEqYzYiWFFwBZy',
          ],
        },
        content: {
          entries: [
            {
              rank: 1,
              contestantJid: 'JIDUSERGlmCGUBw0xYxzV2u2X6l',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERGlmCGUBw0xYxzV2u2X6l-be281652c9e4a38731fc5ccf9ba46391.png',
              totalAccepted: 4,
              totalPenalties: 164,
              lastAcceptedPenalty: 3886107,
              attemptsList: [2, 1, 1, 2],
              penaltyList: [32, 8, 43, 65],
              problemStateList: [1, 2, 1, 2],
            },
            {
              rank: 2,
              contestantJid: 'JIDUSERXWcpYoJpRKk6hhbgueoY',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERXWcpYoJpRKk6hhbgueoY-3969bdbcfca238425ac2d274ebab2e9f.jpg',
              totalAccepted: 4,
              totalPenalties: 207,
              lastAcceptedPenalty: 5447490,
              attemptsList: [1, 1, 1, 1],
              penaltyList: [18, 33, 65, 91],
              problemStateList: [1, 1, 1, 1],
            },
            {
              rank: 3,
              contestantJid: 'JIDUSERoAyCGh5EKkmEWGXQKO96',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERoAyCGh5EKkmEWGXQKO96-f3837d65efe9c47d2ed1543a5b8cf7ed.jpg',
              totalAccepted: 4,
              totalPenalties: 254,
              lastAcceptedPenalty: 6028480,
              attemptsList: [1, 2, 2, 1],
              penaltyList: [101, 18, 43, 76],
              problemStateList: [1, 1, 1, 1],
            },
            {
              rank: 4,
              contestantJid: 'JIDUSERD7Ngp13Cga22wnUqoRdB',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERD7Ngp13Cga22wnUqoRdB-da60991e00b94d632af0fcaf356682cf.png',
              totalAccepted: 3,
              totalPenalties: 133,
              lastAcceptedPenalty: 4099647,
              attemptsList: [2, 3, 1, 0],
              penaltyList: [13, 69, 27, 0],
              problemStateList: [2, 1, 2, 0],
            },
            {
              rank: 5,
              contestantJid: 'JIDUSERTBoPsmm8OZmEr16TbBjY',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERTBoPsmm8OZmEr16TbBjY-465f63f8a4ad7c843bfb5564ad6ac3a0.png',
              totalAccepted: 3,
              totalPenalties: 181,
              lastAcceptedPenalty: 5474520,
              attemptsList: [1, 1, 3, 0],
              penaltyList: [48, 25, 92, 0],
              problemStateList: [1, 1, 1, 0],
            },
            {
              rank: 6,
              contestantJid: 'JIDUSERJcxgDZopxunhw90d9iOs',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 3,
              totalPenalties: 221,
              lastAcceptedPenalty: 6427418,
              attemptsList: [1, 4, 1, 0],
              penaltyList: [25, 64, 108, 0],
              problemStateList: [1, 1, 1, 0],
            },
            {
              rank: 7,
              contestantJid: 'JIDUSERPZWw75l5mNsTVEOejf4n',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 3,
              totalPenalties: 231,
              lastAcceptedPenalty: 7068866,
              attemptsList: [2, 1, 3, 0],
              penaltyList: [38, 51, 118, 0],
              problemStateList: [1, 1, 1, 0],
            },
            {
              rank: 8,
              contestantJid: 'JIDUSERhVBTSxwCH2GSyK7I6gv2',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERhVBTSxwCH2GSyK7I6gv2-06b4da756e0784fd53f33f67f99a8d1c.jpg',
              totalAccepted: 2,
              totalPenalties: 87,
              lastAcceptedPenalty: 3135952,
              attemptsList: [0, 2, 1, 0],
              penaltyList: [0, 26, 53, 0],
              problemStateList: [0, 1, 1, 0],
            },
            {
              rank: 9,
              contestantJid: 'JIDUSERsPS40FNl2K6RIYKpeXsN',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERsPS40FNl2K6RIYKpeXsN-4bc78781eed392715ccc4bf544911b9c.png',
              totalAccepted: 2,
              totalPenalties: 114,
              lastAcceptedPenalty: 5223719,
              attemptsList: [1, 0, 2, 0],
              penaltyList: [18, 0, 88, 0],
              problemStateList: [1, 0, 1, 0],
            },
            {
              rank: 10,
              contestantJid: 'JIDUSERh8wo7Brlikbdg9McXQUt',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 2,
              totalPenalties: 145,
              lastAcceptedPenalty: 4158780,
              attemptsList: [2, 2, 1, 0],
              penaltyList: [59, 70, 120, 0],
              problemStateList: [1, 1, 0, 0],
            },
            {
              rank: 11,
              contestantJid: 'JIDUSER8RTu0pGquVp25C3NTKUy',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 2,
              totalPenalties: 151,
              lastAcceptedPenalty: 5499739,
              attemptsList: [1, 2, 0, 0],
              penaltyList: [51, 92, 0, 0],
              problemStateList: [1, 1, 0, 0],
            },
            {
              rank: 12,
              contestantJid: 'JIDUSERE5wWRfP11XQf6fzExoba',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERE5wWRfP11XQf6fzExoba-df5ca814ee02d3a76f225e0c91aea181.jpg',
              totalAccepted: 2,
              totalPenalties: 156,
              lastAcceptedPenalty: 5578899,
              attemptsList: [2, 2, 0, 0],
              penaltyList: [47, 93, 0, 0],
              problemStateList: [1, 1, 0, 0],
            },
            {
              rank: 13,
              contestantJid: 'JIDUSERienP80NzcpzJRNn18BLY',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERienP80NzcpzJRNn18BLY-7ea1103b3796b5f361b6eee05c4be8ed.jpg',
              totalAccepted: 1,
              totalPenalties: 30,
              lastAcceptedPenalty: 1766033,
              attemptsList: [1, 5, 0, 0],
              penaltyList: [30, 109, 0, 0],
              problemStateList: [1, 0, 0, 0],
            },
            {
              rank: 14,
              contestantJid: 'JIDUSERkeeAF95bYeD6u97mAxzg',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERkeeAF95bYeD6u97mAxzg-b70cf5b4c95b17605e70242aeda71bad.png',
              totalAccepted: 1,
              totalPenalties: 58,
              lastAcceptedPenalty: 2008392,
              attemptsList: [4, 0, 0, 0],
              penaltyList: [34, 0, 0, 0],
              problemStateList: [1, 0, 0, 0],
            },
            {
              rank: 15,
              contestantJid: 'JIDUSER9oCEQ1fKKtE0JnOZR29K',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSER9oCEQ1fKKtE0JnOZR29K-0e81e7741a47867be1ffbd2f5758f8a0.jpg',
              totalAccepted: 1,
              totalPenalties: 63,
              lastAcceptedPenalty: 3271674,
              attemptsList: [2, 0, 0, 0],
              penaltyList: [55, 0, 0, 0],
              problemStateList: [1, 0, 0, 0],
            },
            {
              rank: 16,
              contestantJid: 'JIDUSERJLZZSzn5PY5GzwsThtZu',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERJLZZSzn5PY5GzwsThtZu-ce4123a5584c19834ce55b6fa67b3eaa.jpg',
              totalAccepted: 1,
              totalPenalties: 80,
              lastAcceptedPenalty: 2839919,
              attemptsList: [5, 1, 0, 0],
              penaltyList: [48, 108, 0, 0],
              problemStateList: [1, 0, 0, 0],
            },
            {
              rank: 17,
              contestantJid: 'JIDUSER42qWD0mRHUBoQMKZDpAF',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 1,
              totalPenalties: 84,
              lastAcceptedPenalty: 5011348,
              attemptsList: [1, 6, 0, 0],
              penaltyList: [84, 107, 0, 0],
              problemStateList: [1, 0, 0, 0],
            },
            {
              rank: 18,
              contestantJid: 'JIDUSERJdEZFy6xHecsRTPFYk3H',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 1,
              totalPenalties: 95,
              lastAcceptedPenalty: 4706574,
              attemptsList: [3, 0, 0, 3],
              penaltyList: [79, 0, 0, 118],
              problemStateList: [1, 0, 0, 0],
            },
            {
              rank: 19,
              contestantJid: 'JIDUSERn4IxlLzfGuBUpFBy7UyQ',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 1,
              totalPenalties: 104,
              lastAcceptedPenalty: 4783535,
              attemptsList: [0, 0, 0, 4],
              penaltyList: [0, 0, 0, 80],
              problemStateList: [0, 0, 0, 1],
            },
            {
              rank: 20,
              contestantJid: 'JIDUSERtDpxAAX1zVxlSdN7lCzS',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 1,
              totalPenalties: 112,
              lastAcceptedPenalty: 5739386,
              attemptsList: [3, 0, 0, 0],
              penaltyList: [96, 0, 0, 0],
              problemStateList: [1, 0, 0, 0],
            },
            {
              rank: 21,
              contestantJid: 'JIDUSEROynAxKKoyXlzpLsMWnfd',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 1,
              totalPenalties: 118,
              lastAcceptedPenalty: 6098302,
              attemptsList: [3, 0, 0, 6],
              penaltyList: [102, 0, 0, 117],
              problemStateList: [1, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERiH4xoeadIspc3gT7uco4',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 9],
              penaltyList: [0, 0, 0, 74],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERgVH6XjgbXOgSwVBfZ9og',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 7],
              penaltyList: [0, 0, 0, 54],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERRcheGWFnarBwDfdjYFa7',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [6, 0, 0, 0],
              penaltyList: [119, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERhFJ5AWTo1ytMJocljeOv',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 3],
              penaltyList: [0, 0, 0, 43],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERxzoyyxjddCEkJbyfiiPq',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 2],
              penaltyList: [0, 0, 0, 118],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSER81DZGVqCEad8H4J8rVAQ',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 2],
              penaltyList: [0, 0, 0, 30],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSER33KcvmaGmuetUCBpNX7G',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSER33KcvmaGmuetUCBpNX7G-1f86f188d51b46f63096c2317c7a30e9.jpg',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 2],
              penaltyList: [0, 0, 0, 32],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERqwbgjFOfFjhJ0MtKotW2',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [2, 0, 0, 0],
              penaltyList: [109, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERSkRMybWchRPsvT1VGr9H',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 2],
              penaltyList: [0, 0, 0, 28],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERZv70HP159YTrBfRlzW9p',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERZv70HP159YTrBfRlzW9p-02307330ef7b538ee6c8ae21e4edafb9.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 1, 0, 0],
              penaltyList: [0, 60, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSER0epnAT3IcXQ1nbYkCfOm',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSER0nMdNeSltPiYfrGSE3pZ',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSER0nMdNeSltPiYfrGSE3pZ-3613be737fead250179835d6f7fc1c85.jpg',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSER1I8LpKYrMiclFRuGTYrS',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSER1I8LpKYrMiclFRuGTYrS-f2ee555df95aca5fb08b891dddb1adf4.jpg',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSER1x5wqMWEWEvGnovq7sEi',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSER3Jhvm5QLZQ3VcWMkw0vN',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSER4yCUZyjlw2D3fuEzu7zD',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSER60MK5c4MOMOfkdf53Ic0',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSER6KyCDKKgKUAw046qhcZG',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSER7iAYDteUK3UwwIL2cczM',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSER7zp3Oyzz5AXvvgo3BPL4',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSER7zp3Oyzz5AXvvgo3BPL4-477fe55a183e5670fd532a5716bf51ef.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSER85iNAEW9xc9UGav9szTE',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSER879uH95bu810RPzgLNTb',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERFHDMUOtwvOTaNE0GaqFo',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERGDm3mCGpS7EbKzTvE9HW',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERGorv5qj5z89TdGKKhtRG',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERGorv5qj5z89TdGKKhtRG-4831df3ee5bddac303080f0741c4b5d2.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERIzEJ6c4zrIouxqzXlPWg',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERKiRDEllRg7skebP6UReR',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERLHBNbjk5qul9Bpo8GmTX',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERMZCSsueJmWtM5dQIkSOj',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERMZCSsueJmWtM5dQIkSOj-427814d3c70e6684cd68de4bc29a37ef.jpg',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSEROj48xZk6KsRZy5s0QmfB',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSEROj48xZk6KsRZy5s0QmfB-a2f4dd5646fa6c0db8b59f4b4d1615eb.jpg',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERPxrj0ieeBzpp1flGqdPU',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERRF9rBojUG04DSot4VGsc',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERRhz06Gl6SXmcv6ZUPAyu',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERRhz06Gl6SXmcv6ZUPAyu-2b83b8e82e66c2157b53335cef81f97a.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERS411IaQ6lJhDtefKhFUd',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERS411IaQ6lJhDtefKhFUd-44c890593cbd2faeccb9f34e939c555a.jpg',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERSStscU2RqwX7DKjjk3dD',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERSqxFDHD77z1nlmDW7OxD',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERSqxFDHD77z1nlmDW7OxD-ac7f782625ff4677beed1dd1fe40529d.jpg',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERUKGmqNcFIqcSsrne988Y',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERUKGmqNcFIqcSsrne988Y-8176e1684eb3422189e07b586a61b5ce.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERUzkzdjaDAqM596JLhFt9',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERViHvJNi8EhnNxjUK5ZyC',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERViHvJNi8EhnNxjUK5ZyC-88f907955b94891ce14dd78ef651b296.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERVyLJL2DjuA3Ys54yuLV0',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERXJ1gWHRj4cTPTsUciuRo',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERXOZYXggJhdm2RGTL2egV',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERYZiw8A3jiXwYOrDrnCy7',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERYZiw8A3jiXwYOrDrnCy7-f8bee655df32c3cb2bea8cfa8bb1581e.jpg',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERc6seSfTUJeSs0Jsi6uYB',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSEReHkKO0DV0KgXdtqAkoXd',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSEReHkKO0DV0KgXdtqAkoXd-a4fb5c8e0e22002b1639d81b1ec8a8c8.jpg',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERgUoEpjt47hKFz5ij6WNS',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERhI2lC8C20KE2RDrR0dGW',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERhyRz01fskYF7Gj2XLnZt',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERhyRz01fskYF7Gj2XLnZt-e1a5a46762568ee359f626da47cdbdb5.jpg',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERkCDlQedJnAffc8ucgQtC',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERlikfw0HNMEGJ5HHd6lGE',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERlmInid8Lmj3Fyv6rdWeq',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERlmInid8Lmj3Fyv6rdWeq-49d532d10ed075cb6fe45a470f438415.jpg',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERmwcEsRnPtQyf936SUPw0',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERmwcEsRnPtQyf936SUPw0-63a9e88d1c0edd68cfb6de7018ed50d6.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERmzA41uQY72KePflz6eFl',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERmzA41uQY72KePflz6eFl-cd70eb013bd17bf3b215de1fdec8c2d1.jpg',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERoKzCRg1P0h1cpcD5s41c',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERoWFiYqBEqYzYiWFFwBZy',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERpUSFkNO1M2D1sRIN84CQ',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERpUSFkNO1M2D1sRIN84CQ-4b9c8be188f83490b2e317b2d4e7dfb1.jpg',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERpWfBjoZumnBAKLJtS1xF',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERqCYx5bNEiqDUZmHh2gwt',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERqRUN48KalIyixTohoIHm',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERr6x104iovUOK9yMSbGoS',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERr6x104iovUOK9yMSbGoS-587e25a6f5619771022a7c3c47b3d330.jpeg',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERs1V040j130IYPEgxwT3j',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERs1V040j130IYPEgxwT3j-21cb9c64ff78428609b829e26147eeb4.jpg',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERtORqD8jwG0VvBtmZN9j3',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERtY060SxILRxz550xcoLo',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERtY060SxILRxz550xcoLo-d1c69a4d6a28fa9d33466492ba0c79f5.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERtgjLPPOIGjWWdUcCpgwD',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERtgjLPPOIGjWWdUcCpgwD-1f1eb49032b5f001fe8d7ea46cd7d239.jpg',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERujnnfIDDZitVfyzs6LUg',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERujnnfIDDZitVfyzs6LUg-adda4ba9380b515e138fe2cc2888956c.jpg',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERwCPFoF0Q95jnl9qEbaMP',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERwCPFoF0Q95jnl9qEbaMP-11af4a646867be0aa8ef3646064dc761.jpg',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERwePsXnTv0jxTcrrce0Jw',
              imageURL: 'https://sso.ia-toki.org/api/v1/users/avatar/avatar-default.png',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
            {
              rank: 22,
              contestantJid: 'JIDUSERxUqhX6BIfzerWDHWphK4',
              imageURL:
                'https://sso.ia-toki.org/api/v1/users/avatar/JIDUSERxUqhX6BIfzerWDHWphK4-2dc8bd77cfda5f45a5a8e83c74437a1f.jpg',
              totalAccepted: 0,
              totalPenalties: 0,
              lastAcceptedPenalty: 0,
              attemptsList: [0, 0, 0, 0],
              penaltyList: [0, 0, 0, 0],
              problemStateList: [0, 0, 0, 0],
            },
          ],
        },
      });
    },
  };
}
