name: ci

on:
  push:
    branches:
      - v1

jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Use Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Test Jophiel
        run: ./judgels-backends/gradlew -p judgels-backends :michael:jophiel-app:check

      - name: Test Sandalphon
        run: ./judgels-backends/gradlew -p judgels-backends/sandalphon check

      - name: Test Uriel
        run: ./judgels-backends/gradlew -p judgels-backends :michael:uriel-app:check

      - name: Test Jerahmeel
        run: ./judgels-backends/gradlew -p judgels-backends :michael:jerahmeel-app:check

      - name: Test Gabriel
        run: ./judgels-backends/gradlew -p judgels-backends/gabriel check

      - name: Set up Node
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 10.16

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Test Raphael
        run: yarn --cwd=`pwd`/judgels-frontends/raphael install && yarn --cwd=`pwd`/judgels-frontends/raphael ci

  build:
    needs: test
    runs-on: ubuntu-20.04
    env:
      CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      CONTAINER_REGISTRY_TOKEN: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50

      - name: Set up Docker
        run: pipx inject ansible-core docker six

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Use Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Jophiel
        run: ./deployment/scripts/build_jophiel.sh

      - name: Build Sandalphon
        run: ./deployment/scripts/build_sandalphon.sh

      - name: Build Uriel
        run: ./deployment/scripts/build_uriel.sh

      - name: Build Jerahmeel
        run: ./deployment/scripts/build_jerahmeel.sh

      - name: Build Gabriel
        run: ./deployment/scripts/build_gabriel.sh

      - name: Set up Node
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 10.16

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build Raphael
        run: ./deployment/scripts/build_raphael.sh
